### ISSUE TITLE
how to set the weather of simulation in BeamNG by BeamNGpy

### ISSUE THREAD

**Issue by lsm2842035890** [BeamNG/BeamNGpy#281] opened 2024-09-09 12:32 UTC
![EU%~}`8H6QBHN)EQ3BK{DDL](https://github.com/user-attachments/assets/ba0ca4be-a60f-48d4-a322-608a127f9932)
I find weather.lua in BeamNG，but i dont find art/defaults.json
My BeamNG version is 0.31.3.0
![2H8PK98~3D6 {9IKPU2_)XM](https://github.com/user-attachments/assets/cb652a75-4fbc-4792-b8ae-971e48729f43)
how can i set the preset in this api? set_weather_preset 's first parameter is path of preset file?

**Comment by aivora-beamng** [comment] 2024-09-11 13:42
Hi, this is a duplicate of https://github.com/BeamNG/BeamNGpy/issues/242, please find the answer there.

**Closed by aivora-beamng** 2024-09-11 13:42 UTC
